[Feature] Admin Dashboard Login Page
LaurierHawkHacks/Dashboard pull request #4
Opened 2023-11-11 21:47 UTC by teoh4770

### Task Description
Given someone in the team navigates to [admin.hawkhacks.ca](http://admin.hawkhacks.ca/) and is not authenticated, then the login page should open. Use Firebase Authentication. Use /login for the login page.

### Tasks Done
- create a form that allows user to sign in with email and password.
- create routes for both /admin and /login, for admin page and login page respectively.
- connect the application with firebase auth.

### Future Improvement

- [ ] prevent user to go to the admin page directly.
- [ ] tidy up the code structure.
- [ ] add specific error message when the user fails to login.
- [ ] do component testing.

2023-11-11 23:07 UTC, juancwu requested changes

2023-11-11 23:07 UTC, juancwu commented on src/utils/Router.tsx
> +        // Todo: user cannot directly go to this admin page
The `/admin` route is not protected.

2023-11-11 23:07 UTC, juancwu commented on src/utils/RequiredAuth.tsx
Might want to take a look at this (https://reactrouter.com/en/main/hooks/use-navigate) instead of using the component.

2023-11-11 23:07 UTC, juancwu commented on src/utils/RequiredAuth.tsx
I might have missed where this is being used, are you importing it anywhere? I assume you want to use this to protect the `/admin` route.

2023-11-11 23:07 UTC, juancwu commented on src/pages/LoginPage.css
Please remove empty file. :)

2023-11-11 23:08 UTC, juancwu commented
Oops, forgot to read your PR description before reviewing but I think you should aim to finish it all in this PR.

2023-11-12 00:41 UTC, teoh4770 commented on src/components/Button/Button.styles.ts
ogeh

2023-11-12 00:42 UTC, teoh4770 commented on src/App.tsx
which button? the button in the login form?

2023-11-12 00:43 UTC, teoh4770 commented on src/index.css
> +        @apply w-full h-full bg-slate-200;
bruh

2023-11-12 23:16 UTC, juancwu requested changes

2023-11-12 23:16 UTC, juancwu commented on src/providers/AuthProvider.tsx
> +    };
```suggestion
    const login = async (email: string, password: string) => {
        const { user } = await signInWithEmailAndPassword(auth, email, password);
        setCurrentUser(user);
    };
```

2023-11-12 23:16 UTC, juancwu commented on src/pages/admin/LoginPage.tsx
> +            setError(null);
```suggestion
```

2023-11-12 23:16 UTC, juancwu commented on src/pages/admin/LoginPage.tsx
> +            authProvider.login(userCredential.user);
```suggestion
await authProvider.login(email, password);
```

2023-11-13 02:31 UTC, teoh4770 commented on src/providers/AuthProvider.tsx
> +    });
any reason you return "unsub" in the useEffect hook?

2023-11-13 12:18 UTC, aidantrabs commented
I updated main for better formatting. Pull from main and update your changes, following the same patterns and router implemented. 

i.e update, imports / exports, naming schemes, and routes

Submit another PR after you make the changes. 🥳

2023-11-13 12:18 UTC, closed without merging